### ISSUE TITLE
images gets loaded from the wrong series. 

### ISSUE THREAD

**Issue by CuddleBear92** [Cazzar/ShokoMetadata.bundle#8] opened 2017-04-17 17:53 UTC
it seems some series if not many can load the wrong images from the wrong series. eventhough the rest of the info is correct. this seems to be mostly covers and fanart/background images this happens too.

**Comment by Cazzar** [comment] 2017-04-19 04:22
I'd need examples of Shoko's API responses and if the images are correct.

The other thing is in the edit screen does the correct images show as an option to change in the edit screen shoe correct?

**Comment by CuddleBear92** [comment] 2017-04-20 13:11
yes, every time I edit on plex it shows up correctly there. I just need to change it. it's just a pain. 
abit afraid to refresh all metadata because of it too as images are not locked on the plex side.


anyway i can help with those responses? run me down on how and ill do it :D

**Comment by Cazzar** [comment] 2017-04-20 15:26
From debugging with @AreFinstad I have found that plex recycles the Metadata object, with some trash in there already

Logs follow:

```2017-04-20 17:22:34,125 (1220c) :  INFO (logkit:16) - poster: http://127.0.0.1:8111/api/image/1/9310
2017-04-20 17:22:34,127 (1220c) :  INFO (logkit:16) - poster: http://127.0.0.1:8111/api/thumb/1/6032/0.6667
2017-04-20 17:22:34,127 (1220c) :  DEBUG (networking:166) - Requesting 'http://127.0.0.1:8111/api/image/7/608'
2017-04-20 17:22:34,134 (1220c) :  INFO (logkit:16) - http://127.0.0.1:8111/api/image/7/531
2017-04-20 17:22:34,134 (1220c) :  INFO (logkit:16) - http://127.0.0.1:8111/api/image/7/532
2017-04-20 17:22:34,134 (1220c) :  INFO (logkit:16) - http://127.0.0.1:8111/api/image/7/540
2017-04-20 17:22:34,134 (1220c) :  INFO (logkit:16) - http://127.0.0.1:8111/api/image/7/537
2017-04-20 17:22:34,134 (1220c) :  INFO (logkit:16) - http://127.0.0.1:8111/api/image/7/5362017-04-20 17:22:34,125 (1220c) :  INFO (logkit:16) - poster: http://127.0.0.1:8111/api/image/1/9310
2017-04-20 17:22:34,127 (1220c) :  INFO (logkit:16) - poster: http://127.0.0.1:8111/api/thumb/1/6032/0.6667
2017-04-20 17:22:34,127 (1220c) :  DEBUG (networking:166) - Requesting 'http://127.0.0.1:8111/api/image/7/608'
2017-04-20 17:22:34,134 (1220c) :  INFO (logkit:16) - http://127.0.0.1:8111/api/image/7/531
2017-04-20 17:22:34,134 (1220c) :  INFO (logkit:16) - http://127.0.0.1:8111/api/image/7/532
2017-04-20 17:22:34,134 (1220c) :  INFO (logkit:16) - http://127.0.0.1:8111/api/image/7/540
2017-04-20 17:22:34,134 (1220c) :  INFO (logkit:16) - http://127.0.0.1:8111/api/image/7/537
2017-04-20 17:22:34,134 (1220c) :  INFO (logkit:16) - http://127.0.0.1:8111/api/image/7/536
2017-04-20 17:22:34,134 (1220c) :  INFO (logkit:16) - http://127.0.0.1:8111/api/image/7/539
2017-04-20 17:22:34,134 (1220c) :  INFO (logkit:16) - http://127.0.0.1:8111/api/image/7/607
2017-04-20 17:22:34,135 (1220c) :  INFO (logkit:16) - http://127.0.0.1:8111/api/image/7/606
2017-04-20 17:22:34,135 (1220c) :  INFO (logkit:16) - http://127.0.0.1:8111/api/image/7/605
2017-04-20 17:22:34,135 (1220c) :  INFO (logkit:16) - http://127.0.0.1:8111/api/image/7/604
2017-04-20 17:22:34,135 (1220c) :  INFO (logkit:16) - http://127.0.0.1:8111/api/image/7/609
2017-04-20 17:22:34,135 (1220c) :  INFO (logkit:16) - http://127.0.0.1:8111/api/image/7/608
2017-04-20 17:22:34,135 (1220c) :  INFO (logkit:16) - http://127.0.0.1:8111/api/image/7/610
2017-04-20 17:22:34,137 (1220c) :  INFO (logkit:16) - http://127.0.0.1:8111/api/image/7/611
2017-04-20 17:22:34,137 (1220c) :  INFO (logkit:16) - http://127.0.0.1:8111/api/image/7/612
2017-04-20 17:22:34,137 (1220c) :  INFO (logkit:16) - http://127.0.0.1:8111/api/image/7/613
2017-04-20 17:22:34,194 (1220c) :  DEBUG (model:229) - Serializing to D:\Programs\Plex Local Data
2017-04-20 17:22:34,134 (1220c) :  INFO (logkit:16) - http://127.0.0.1:8111/api/image/7/539
2017-04-20 17:22:34,134 (1220c) :  INFO (logkit:16) - http://127.0.0.1:8111/api/image/7/607
2017-04-20 17:22:34,135 (1220c) :  INFO (logkit:16) - http://127.0.0.1:8111/api/image/7/606
2017-04-20 17:22:34,135 (1220c) :  INFO (logkit:16) - http://127.0.0.1:8111/api/image/7/605
2017-04-20 17:22:34,135 (1220c) :  INFO (logkit:16) - http://127.0.0.1:8111/api/image/7/604
2017-04-20 17:22:34,135 (1220c) :  INFO (logkit:16) - http://127.0.0.1:8111/api/image/7/609
2017-04-20 17:22:34,135 (1220c) :  INFO (logkit:16) - http://127.0.0.1:8111/api/image/7/608
2017-04-20 17:22:34,135 (1220c) :  INFO (logkit:16) - http://127.0.0.1:8111/api/image/7/610
2017-04-20 17:22:34,137 (1220c) :  INFO (logkit:16) - http://127.0.0.1:8111/api/image/7/611
2017-04-20 17:22:34,137 (1220c) :  INFO (logkit:16) - http://127.0.0.1:8111/api/image/7/612
2017-04-20 17:22:34,137 (1220c) :  INFO (logkit:16) - http://127.0.0.1:8111/api/image/7/613```

The issue is in the agent.
A fix for this would be clearing metadata's pictures.

**Comment by CuddleBear92** [comment] 2017-06-18 16:25
leaving the current workaround here if someone might need it.

1. Delete the Library with the anime.

2. Delete the com.plexapp.agents.shoko cache folder. (\Plug-in Support\Caches\com.plexapp.agents.shoko) you can find it easily by right clicking plex in taskbar and opening the plugins folder.

3. Clean Plex Bundles (server as a whole) 
![image](https://user-images.githubusercontent.com/8496821/27262271-71d595c4-5453-11e7-87bb-ad5b912a8623.png)

4. Make new Library for your Shoko Metadata Agent and Enjoy!

**Comment by Cazzar** [comment] 2017-08-14 16:32
https://github.com/Cazzar/ShokoMetadata.bundle/commit/5c4e04990d28cd702e4462d2a18ae9a25923442f

**Closed as completed by Cazzar** 2017-08-14 16:32 UTC
Labels: bug, help wanted
